(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A2=function(a){a.S("cardstatechange",g.pN(a)&&g.qN(a)?1:0)},$va=function(a){var b=g.Ph(a);
a=g.Wh(a);return new g.yh(b.x,b.y,a.width,a.height)},awa=function(a){return Math.pow(a,3)},bwa=function(a){return 3*a*a-2*a*a*a},B2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Gk:g.Cs(a),kk:a};"UNDEFINED_CSN"==a?g.Qs("visualElementShown",d,e):c?g.Xp("visualElementShown",d,c,e):g.or("visualElementShown",d,e)})},C2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Gk:g.Cs(a),kk:a,kG:e};"UNDEFINED_CSN"==a?g.Qs("visualElementHidden",d,e):c?g.Xp("visualElementHidden",d,c,e):g.or("visualElementHidden",d,e)})},F2=function(a){a=g.Ra(a);
delete D2[a];g.Ob(D2)&&E2&&E2.stop()},dwa=function(){E2||(E2=new g.G(function(){cwa()},20));
var a=E2;a.isActive()||a.start()},cwa=function(){var a=(0,g.E)();
g.Ab(D2,function(b){ewa(b,a)});
g.Ob(D2)||dwa()},G2=function(a,b,c,d){g.Ln.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},ewa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;fwa(a,a.progress);1==a.progress?(a.o=0,F2(a),a.Ad(),a.Dn()):a.sb()&&a.vv()},fwa=function(a,b){g.Oa(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},gwa=function(a,b){g.Qe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},I2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},J2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},K2=function(a){return a.baseUrl||null},L2=function(a,b){return(0,g.Ce)((0,g.Lc)(a,b,void 0),function(c){return!!c})},hwa=function(a,b,c){function d(ac){var Nb=ac.hovercardButton;
if(!Nb)return null;Nb=Nb.subscribeButtonRenderer;if(!Nb)return null;var Te=f(Nb.unsubscribedButtonText),Zn=f(Nb.subscribedButtonText);if(Nb.subscribed){var $n=f(Nb.subscriberCountWithUnsubscribeText);var ao=f(Nb.subscriberCountText)}else $n=f(Nb.subscriberCountText),ao=f(Nb.subscriberCountWithSubscribeText);var yj=null;return ac.signinEndpoint&&(yj=g.Ib(ac,"signinEndpoint","webNavigationEndpointData","url"),!yj)?null:Te&&(Zn||yj)?{subscribed:Nb.subscribed,subscribeText:Te,subscribeCount:$n,unsubscribeText:Zn,
unsubscribeCount:ao,enabled:Nb.enabled,signinUrl:yj,classic:ac.useClassicSubscribeButton}:null}
function e(ac){if(ac){var Nb=[],Te=ac.videoId;Te&&Nb.push("v="+Te);(Te=ac.playlistId)&&Nb.push("list="+Te);(ac=ac.startTimeSeconds)&&Nb.push("t="+ac);return"/watch?"+Nb.join("&")}}
function f(ac){if(!ac)return null;var Nb=ac.simpleText;return Nb?Nb:ac.runs?(0,g.Lc)(ac.runs,function(Te){return Te.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,B=!1,z=null,D=null,F=null,H=null,U=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(B=g.Ib(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Ib(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(U=f(b.additionalFeesText)),(n=g.Ib(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Ib(b,"title","accessibility","accessibilityData","label");var Z=b.endpoint?b.endpoint.clickTrackingParams:null,nc="";if(b.metadata){var oc=f(b.metadata);oc&&(nc=oc)}return{id:"element-"+c,type:h,title:f(b.title),metadata:nc,callToAction:f(b.callToAction),
Ny:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:z,subscribersText:D,isSubscribe:B,targetUrl:m,BH:n,Bc:{itct:Z},cP:q,em:a?a:null,FH:b.isPlaceholder,impressionUrls:L2(b.impressionUrls||[],K2),sH:L2(b.hovercardShowUrls||[],K2),clickUrls:L2(l.loggingUrls||[],K2),visualElement:g.vs(b.trackingParams),productPrice:H,
additionalFeesText:U}},M2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=L2(a.impressionUrls||[],K2);a.trackingParams&&(c.visualElement=g.vs(a.trackingParams));c.elements=L2(a.elements||[],function(d,e){return hwa(b,d,e)});
return c},N2=function(a){g.NN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.py(a)||g.ry(a);this.R=!0;this.I=0;this.C=new g.es(this);g.C(this,this.C);this.C.L(this.player,g.$y("creatorendscreen"),this.hI);this.C.L(this.player,"crx_creatorendscreen",this.iI);this.C.L(this.player,"resize",this.JA);this.C.L(window,"focus",this.WN);this.load();var b=g.we("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ne(this,function(){g.Be(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},iwa=function(a){return a.player.getVideoData().fc?"current":a.N?"new":"current"},O2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},P2=function(a,b,c){c=void 0===c?!0:c;
g.rQ(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&jwa(a);c=[];d=new g.Xy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.T({D:"div",J:"ytp-ce-shadow"}),g.zN(a.player,a.A.element,4),a.F=new g.hO(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=kwa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.zN(a.player,f.element,4);var h=new g.Xy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);lwa(a,f,e)}g.vN(a.player,c);
a.JA()}},jwa=function(a){var b=g.zs(),c=g.Bs();
c&&b&&a.u.visualElement&&g.Ws(c,b,a.u.visualElement)},kwa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.em||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:Q2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Rn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.em||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:Q2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Rn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.em||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Rn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)}]};c=new g.T(c);var d=g.ie(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Bc.itct}else e="endscreen",f=null;e=new g.qP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.em||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Rn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:mwa(b.iconUrl)}]};c=new g.T(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.em||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Rn(b.title||"")},V:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.T(c)}b.FH&&g.I(c.element,"ytp-ce-placeholder");return c},Q2=function(a){if(a.Ny)var b=a.Ny.thumbnails;
return mwa(b?b[b.length-1].url:null)},mwa=function(a){return a?{style:"background-image: url("+a+")"}:{}},lwa=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.ma("mouseenter",(0,g.x)(a.Qu,a,b,c));b.ma("mouseleave",(0,g.x)(a.Bv,a,b,c));a.player.O().o||b.ma("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ma("click",(0,g.x)(a.VB,a,c));b.ma("keypress",(0,g.x)(a.VB,a,c));b.ma("focus",(0,g.x)(function(l,m){this.Qu(l,m)},a,b,c));
b.ma("blur",(0,g.x)(function(l,m){this.Bv(l,m)},a,b,c));
b.ma("touchstart",(0,g.x)(a.Qu,a,b,c));var f=g.ke("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Jn(b.element,"ytp-ce-element-hover");g.Jn(b.element,"ytp-ce-force-expand")});
b.ma("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),S2(this,m.id,!0)):(g.Jn(l.element,"ytp-ce-force-expand"),g.Jn(l.element,"ytp-ce-element-hover"),S2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ma("blur",g.Sa(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.ke("ytp-sb-subscribe",b.element));c(g.ke("ytp-sb-unsubscribe",b.element));b.ma("focus",d);b.ma("blur",e)},R2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Vy(c)+b}else return"";return b},S2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},T2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||O2(a))c&&c();else{b=nwa(a,b);var e=0,f=!1,h=new g.G(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Cr(b[a],d)}},U2=function(a,b,c){T2(a,b.clickUrls,c);
(a=g.Bs())&&b.BH&&g.Xs(a,b.visualElement)},nwa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(owa(b[e],c));return d},owa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},pwa=function(a){return Array.isArray(a)&&a.length?a[0]:a},V2=function(a){return"string"===typeof a?a:""},W2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},rwa=function(a){var b=qwa;
if(null==a)return null;if(g.Na(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},swa=function(a){this.externalId=a},twa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},X2=function(a){if(!a)return null;
var b=g.Fc(V2(a.value));b=g.Bc(b);if(!b)return null;var c=W2(a.target,uwa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new twa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Y2=function(a){return a.value?a.value:null},vwa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},qwa=function(a){if(!a)return null;
var b=W2(a.type,wwa),c=W2(a.trigger,xwa),d=pwa(a.url);d=X2(d?d:null);a=pwa(a.subscribeData);var e=a?a:null;e?(a=V2(e.external_user_id),e=V2(e.subscription_token),a=a&&e?new swa(a):null):a=null;return b?new vwa(b,c,d,a):null},Z2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},ywa=function(a,b){return g.cb(a.o,b,void 0)},zwa=function(a){this.o=a},Awa=function(a,b,c){b&&(c?$2(a,(0,g.Lc)(b,g.Sa(function(d,e){return g.nn(e,d)},c))):$2(a,b))},$2=function(a,b,c,d){var e=1,f=-1;
if(c){var h=!1;var l=function(){e--;e||h||(clearTimeout(f),h=!0,c())};
f=setTimeout(function(){h=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Cr(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Bwa=function(a,b){this.context=a;
this.o=b},b3=function(a){return a.customMessage?a3("div","iv-card-message",a.customMessage):""},c3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},d3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.p(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(a3("li","",c.value));return{D:"ul",J:"iv-card-meta-info",K:b}},a3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Rn(c);return{D:a,P:b,V:c}},Cwa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Uo&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Uo+");");c.dir=g.Rn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",W:b,P:c,K:d}},e3=function(a,b,c,d){if(d){b=g.p(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.Bc,c.ae.click,5)}},Dwa=function(a,b){this.merchant=a;
this.price=b},Ewa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Fwa=function(a,b){return b?b:Ewa(a)?"current":"new"},f3=function(a,b){g.A.call(this);
var c=this;this.element=a;this.context=b;this.sa=!1;this.fa=new Map;this.ga=new Map;this.context.H.addEventListener(g.$y("annotations_module"),function(d){(d=c.fa.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.ga.get(d))&&d.apply(c)})},g3=function(a,b,c,d,e,f,h){a.context.o.ma(b,"click",function(){a.Vu(c,d,e,f||[],h||0)});
a.context.o.ma(b,"touchstart",function(){a.sa=!1});
a.context.o.ma(b,"touchmove",function(){a.sa=!0})},Gwa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},h3=function(a,b,c){return{Uz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
ND:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Tr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},k3=function(a,b,c){f3.call(this,b,c);
var d=this;this.H=a;this.eventId=null;this.Z=this.Da=this.A=this.Hc=!1;this.aa=null;this.cards=[];this.va=this.I=this.Y=this.C=this.ea=this.o=null;this.N=[];this.G=this.yc=this.T=null;this.F=0;this.U=new g.G(g.Ka,c.B.gb?4E3:3E3);g.C(this,this.U);this.na=new g.G(g.Ka);g.C(this,this.na);this.R=new Bwa(c,function(e,f,h,l,m,n){g3(d,e,f,h,l,m,n)});
this.M=new g.T({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ra=new g.hO(this.M,330);g.C(this,this.ra);this.ya=g.ke("iv-drawer-header-text",this.B);this.u=g.ke("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Da&&i3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Da=d.A)&&j3(d)})},Hwa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){i3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){j3(a)});
var d=c.headerText;g.Fe(a.ya,d);a.I&&a.I.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.T=g.vs(c.trackingParams);a.G=g.vs(c.closeTrackingParams);a.yc=g.vs(c.iconTrackingParams)},Iwa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.R(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bc:l3(a,c,b,d),sponsored:!1,ae:h3(d,e,d.command),bh:d.trackingParams?g.vs(d.trackingParams):null,uf:e.trackingParams?g.vs(e.trackingParams):
null,yc:f&&f.trackingParams?g.vs(f.trackingParams):null,imageUrl:m3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.R(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Uo:null,title:d.title?g.R(d.title):"",customMessage:d.callToAction?g.R(d.callToAction):"",url:d.command.urlEndpoint.url?X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.command.urlEndpoint.url}):null};n3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.R(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bc:l3(a,c,b,d),sponsored:!1,ae:h3(d,e,d.endpoint),bh:d.trackingParams?g.vs(d.trackingParams):null,uf:e.trackingParams?g.vs(e.trackingParams):null,yc:f&&f.trackingParams?g.vs(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,
customMessage:d.customText?g.R(d.customText):null,TC:m3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.R(d.channelName):"",metaInfo:[d.subscriberCountText?g.R(d.subscriberCountText):""],url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};n3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.R(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bc:l3(a,c,b,d),sponsored:!1,ae:h3(d,e,d.action),bh:d.trackingParams?g.vs(d.trackingParams):null,uf:e.trackingParams?g.vs(e.trackingParams):null,yc:f&&f.trackingParams?g.vs(f.trackingParams):null,jo:m3(d.playlistThumbnail.thumbnails,
258).url,customMessage:d.customMessage?g.R(d.customMessage):null,playlistVideoCount:g.R(d.playlistVideoCount),title:d.playlistTitle?g.R(d.playlistTitle):"",metaInfo:[d.channelName?g.R(d.channelName):"",d.videoCountText?g.R(d.videoCountText):""],url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Gwa(d.action)})};n3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?
b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.R(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bc:l3(a,c,b,d),sponsored:!1,ae:h3(d,e,d.action),bh:d.trackingParams?g.vs(d.trackingParams):null,uf:e.trackingParams?g.vs(e.trackingParams):null,yc:f&&f.trackingParams?g.vs(f.trackingParams):null,jo:m3(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.R(d.lengthString):
null,customMessage:d.customMessage?g.R(d.customMessage):null,title:d.videoTitle?g.R(d.videoTitle):"",metaInfo:[d.channelName?g.R(d.channelName):"",d.viewCountText?g.R(d.viewCountText):""],isLiveNow:!!d.badge,url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Gwa(d.action)})};n3(a,c)}a.F++},m3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},l3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Kwa=function(a,b){var c=Jwa(a,b);
c&&(c===a.o&&(a.o=null),a.H.removeCueRange(c.card.id),g.Be(c.ct),g.kb(a.cards,c),a.Xo(),o3(a))},i3=function(a,b,c){if(!a.A){a.ra.show();
a.ea=new g.G(function(){g.I(a.context.H.getRootNode(),g.ZL.IV_DRAWER_OPEN)},0);
a.ea.start();a.aa=g.hp(a.u,"mousewheel",function(h){a.U.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.Bs();d&&a.T&&a.G&&B2(d,[a.T,a.G]);b={TRIGGER_TYPE:b};for(var e=g.p(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.uA||(f.uA=!0,Awa(a.context.logger,f.card.ae.Uz,b)),d&&B2(d,[f.card.bh]);A2(a.H);c&&(a.C=new g.G(function(){a.Y=a.I;a.va.focus()},330),a.C.start())}},j3=function(a){a.A&&(a.ra.hide(),g.ip(a.aa),a.aa=null,g.Jn(a.context.H.getRootNode(),g.ZL.IV_DRAWER_OPEN),a.A=!1,A2(a.H),a.C&&a.C.stop(),a.C=new g.G(function(){a.Y&&(a.Y.focus(),a.Y=null)},330),a.C.start())},Mwa=function(a){g.In(a.xa(),
[g.ZL.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.zN(a.H,a.B,5);Lwa(a);a.I=g.ke("ytp-cards-button",a.H.getRootNode());a.va=g.ke("iv-drawer-close-button",a.B);a.Hc=!0},Lwa=function(a){var b=g.ke("iv-drawer-close-button",a.B);
a.context.o.ma(b,"click",a.PF,a);a.context.o.ma(a.u,"touchend",function(){a.U.start()});
a.context.o.ma(a.u,"scroll",a.gG,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.Hn(a.H.getRootNode(),"ytp-autohide")});
a.N.push(g.So("iv-button-shown",a.KH,a));a.N.push(g.So("iv-button-hidden",a.JH,a));a.N.push(g.So("iv-teaser-shown",a.UI,a));a.N.push(g.So("iv-teaser-hidden",a.LH,a));a.N.push(g.So("iv-teaser-clicked",a.TI,a))},n3=function(a,b){a.Hc||Mwa(a);
Kwa(a,b.id);var c=Nwa(a,b);if(c){var d={card:b,ct:c.element,uA:!1},e=Owa(a,d);g.rb(a.cards,e,0,d);c.ba(a.u,e);a.Xo();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,o3(a),Pwa(a,d),i3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&Qwa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Qwa(a,d)}),o3(a))}},Nwa=function(a,b){switch(b.type){case "simple":var c=a.R;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",V:b.displayDomain}:void 0;var e=Cwa(b);d={D:"div",W:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:b.url?Y2(b.url)||"":""},K:[c3(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[a3("h2",void 0,b.title),e]}]}]};d=new g.T(d);e3(c,g.je("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.R,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],P:{href:Y2(b.url)||"","data-ytid":b.channelId},K:[c3(b.TC),
{D:"div",J:"iv-card-content",K:[b3(b),{D:"h2",J:"iv-card-primary-link",V:b.title},d3(b)]}]}]},d=new g.T(d),e3(c,g.je("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.R,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:Y2(b.url)||""},K:[c3(b.jo,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[b3(b),a3("h2","iv-card-primary-link",b.title),d3(b)]}]}]},d=new g.T(d),
e3(c,g.je("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.R;var f=!g.gb(b.offers);d=["iv-card"];e="";var h=Cwa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",J:"iv-card-offer-price",V:h.price}),h.merchant&&f.push({D:"div",J:"iv-card-offer-merchant",V:h.merchant}),h={D:"div",K:f});f=b.url?Y2(b.url)||"":"";d={D:"div",W:d,P:{tabindex:"0"},K:[{D:"a",W:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Sponsored",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",V:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:f},K:[a3("h2",e,b.title),h]}]}]};d=new g.T(d);e=g.we("span");g.Fe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Bb(e,"adInfo");e3(c,g.je("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.R,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"LIVE NOW"}:null,d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:Y2(b.url)||""},K:[c3(b.jo,b.videoDuration?{D:"span",J:"iv-card-video-duration",V:b.videoDuration}:void 0),{D:"div",J:"iv-card-content",K:[b3(b),a3("h2","iv-card-primary-link",b.title),d3(b),d]}]}]},d=new g.T(d),e3(c,g.je("iv-click-target",d.element),
b,b.url),d;default:return null}},Owa=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},Rwa=function(a){return a.o?"productListing"===a.o.card.type:(0,g.Ci)(a.cards,function(b){return"productListing"===b.card.type})},o3=function(a){g.J(a.H.getRootNode(),"ytp-cards-shopping-active",Rwa(a))},Qwa=function(a,b){if(!g.Hn(a.H.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.Bs(),d=a.o?a.o.card.yc:a.yc;
c&&d&&C2(c,[d]);a.o=b;o3(a)}if(c="none"!=a.xa().style.display)2===a.context.H.getPresentingPlayerType()?c=1===a.context.H.getAdState():(c=a.context.H.getPlayerState(),d=0===c&&0===a.context.H.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.oN(g.dN(a.H)))&&d.Ou(!0,c));a.na.isActive()||((!a.A||!a.U.isActive()&&a.Z)&&Pwa(a,b),a.na.start(910+b.card.teaserDurationMs))}},Pwa=function(a,b){if(a.M.La()){var c=new G2([0,
a.u.scrollTop],[0,b.ct.offsetTop],600,bwa);a.context.A.ma(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ma(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.YL(a.M,!0),a.u.scrollTop=b.ct.offsetTop,g.YL(a.M,!1)},p3=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},Jwa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},q3=function(a,b,c){f3.call(this,a,b);
this.annotation=c;this.isActive=!1},Swa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},r3=function(a,b,c){q3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},Twa=function(a,b){var c=void 0===c?0:c;
var d=$va(b).width;g.Lh(b,d);c=new I2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,awa);g.C(a,c);a.context.A.ma(c,"begin",function(){g.Xh(b,!0)});
c.play()},Wwa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
W:["iv-branding-context-name"],V:b.channel_name}),d=a.createElement({D:"div",W:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.qP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.H),a.o.ba(d));var f=a.createElement({D:"div",W:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",W:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Xh(h,!1);var l=a.createElement({D:"div",W:["branding-context-container-outer"]});l.appendChild(h);g.Dh(l,"right",b.image_width+"px");a.xa().appendChild(l);a.A=new g.G(function(){Uwa(a,h,l)},500);
g.C(a,a.A);a.context.o.ma(a.xa(),"mouseover",function(){Vwa(a,h,l,f,b.image_height)});
a.context.o.ma(a.xa(),"mouseout",function(){a.A.start()})}},Vwa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Wh(b);a.o||(g.Uh(b,f.width),g.Uh(c,f.width));g.Dh(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Dh(d,"right","1px");a.B=!0;g.Xh(b,!0);a.C=new g.G(function(){g.I(this.xa(),"iv-branding-active")},0,a);
a.C.start()}},Uwa=function(a,b,c){g.Jn(a.xa(),"iv-branding-active");
a.F=new g.G(function(){g.Xh(b,!1);a.o||g.Uh(c,0)},250);
a.F.start();a.B=!1},Xwa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},s3=function(a,b,c){q3.call(this,a,b,c);
var d=this;this.I=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.G=this.createElement({D:"div",W:["iv-promo-contents"]});this.C=new g.G(function(){d.o.setAttribute("aria-hidden","true");g.Xh(d.A,!1);g.Xh(d.u,!0)},700,this);
g.C(this,this.C)},Ywa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden","true");a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.xc(),f=b.image_url;if(f){var h=a.createElement({D:"div",W:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",P:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",J:"iv-promo-video-duration",V:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",V:b.playlist_length.toString()}),h.appendChild(f));e&&g3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.ed(f,Y2(e)),a.o=f):a.o=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_1}]});
var m=a.createElement({D:"p",K:[{D:"span",J:"iv-promo-link",V:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",W:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",W:["iv-button","iv-promo-button"],K:[{D:"span",J:"iv-button-content",V:f}]});var q=a.createElement({D:"div",J:"iv-promo-button-container"});q.appendChild(f);e&&g3(a,a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&
g3(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",K:[{D:"span",V:b.text_line_1}]}),m=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",W:["yt-badge","iv-promo-badge-live"],V:"LIVE NOW"})),g.I(a.o,"iv-click-target"),e&&g3(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);q&&a.G.appendChild(q);c=a.createElement({D:"div",
J:"iv-promo-actions"});a.u=a.createElement({D:"button",W:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.o.ma(a.u,"click",function(r){t3(a,5E3,r)});
c.appendChild(a.u);g.Xh(a.u,!1);a.context.o.ma(a.xa(),"mouseover",a.aH,a);a.context.o.ma(a.xa(),"mouseout",a.ZG,a);a.context.o.ma(a.xa(),"touchend",function(r){t3(a,5E3,r)});
a.A=a.createElement({D:"button",W:["iv-promo-close","ytp-button"]});a.A.title="Close";a.context.o.ma(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.TG:a.SG,a);c.appendChild(a.A);g.In(a.xa(),d);h&&(a.xa().appendChild(h),n&&h.appendChild(n));a.xa().appendChild(a.G);a.xa().appendChild(c)},t3=function(a,b,c){c.stopPropagation();
Zwa(a);$wa(a,b);a.o.focus()},axa=function(a){a.isCollapsed||a.I||a.B||(g.I(a.xa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},Zwa=function(a){a.C.stop();
a.isCollapsed&&(g.Kn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Xh(a.u,!1),g.Xh(a.A,!0))},$wa=function(a,b){a.B||(a.B=g.cg(function(){u3(this);
axa(this)},b,a))},u3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},v3=function(a){g.NN.call(this,a);
this.N=!1;this.M=0;this.G={};this.Y=new zwa(a);this.C=new g.es(this);g.C(this,this.C);this.F=this.A=null;this.C.L(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.L(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.L(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.L(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.L(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.fI,this);this.subscribe("resize",this.jr,this);this.player.O().N.subscribe("vast_info_card_add",this.EC,this);this.T=new g.es(this);g.C(this,this.T);this.U=g.ve("DIV","video-custom-annotations");this.u=new g.T({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.zN(this.player,this.u.element,4);this.u.hide();this.B=new g.T({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.B);g.ye(this.B.element,g.ve("DIV","video-annotations",
this.U));this.I=this.o=null;this.R=[];bxa(this)&&this.load();var b=g.we("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ne(this,function(){g.Be(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},cxa=function(){var a=g.ve("DIV",["annotation",
"annotation-type-custom"]);g.Xh(a,!1);return a},dxa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},bxa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.tE||b.N.get(a.videoId)||g.YB(a)||g.ZB(a)?!0:!1},exa=function(a,b){var c=!b.isCued()&&!g.S(b,1024);
g.YL(a.u,c);g.YL(a.B,c)},fxa=function(a,b,c){a.N=!0;
a.F=g.vq(b,c)},gxa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(gxa(a,e))}return c},hxa=function(a,b,c){return!(a.loaded&&a.M==b&&a.player.getVideoData().videoId==
c)},kxa=function(a){var b=a.player.getVideoData();
if(b.cf){var c=a.player.O().N.get(b.videoId);if(c){var d={format:"XML",Xe:{},method:"POST",withCredentials:!0};d.Ad=(0,g.x)(function(e,f,h){hxa(this,e,f)||(e=g.pq(h)&&h.responseXML?h.responseXML:null)&&w3(this,e)},a,a.M,b.videoId);
g.xp()&&(d.Ad=ixa(a,d.Ad));d.Cb={ic_only:"1"};jxa(d,c);a.N=!0;g.vq(b.cf,d)}}},jxa=function(a,b){a.method="POST";
a.Cb=a.Cb||{};b.ep&&(a.Cb.ic_coll=b.ep);b.fp&&(a.Cb.ic_xml=b.fp);b.no&&(a.Cb.ic_track=b.no)},lxa=function(a){var b=new g.T({D:"div"});
g.Xh(b.element,!1);var c=new k3(a.player,b.element,x3(a));g.C(c,b);b.ba(a.u.element);c.Xn();return c},x3=function(a){if(!a.I){var b=new J2(a);
g.C(a,b);var c=new g.z1(a);g.C(a,c);a.I=new Xwa(b,c,a.player.O(),a.player.getVideoData(),a.Y,a.player,a.Da)}return a.I},w3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Bs();if(e){var f=g.zs();f&&g.Rs(g.Bo("use_default_events_client")?void 0:g.nr,e,f,[g.vs(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=gxa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=W2(h.type,mxa),r=W2(h.style,nxa),u=V2(h.data),w=0!=u.length?JSON.parse(u):{},B=rwa(h.action);f=n&&q?new Z2(n,q,r,B,w):null}else f=null}catch(Z){}if(f){a:{switch(f.type){case "branding":case "promotion":h=
!0;break a}h=!1}if(h){h=a;m=f;var z=cxa(),D=null;switch(m.type){case "branding":if(h.player.O().Ha)break;h.u.element.appendChild(z);D=new r3(z,x3(h),m);break;case "promotion":g.zN(h.player,z,4),D=new s3(z,x3(h),m)}D&&D.Xn();if(h=D)g.C(a,h),a.G[f.id]=h}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=lxa(a),g.C(a,a.o));if("card"==f.type){c=a.o;var F=f&&f.data&&f.data.card_type;h=f.data;if(F)switch(m=h.tracking||{},m={Uz:m.impression,click:m.click,close:m.close,ND:m.teaser_impression,Tr:m.teaser_click},
z=h.tracking_params||{},D=null,F){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,bh:z.card?g.vs(z.card):null,uf:z.teaser?g.vs(z.teaser):null,yc:z.icon?g.vs(z.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,TC:h.image_url,title:h.title,metaInfo:h.meta_info,url:X2({pause_on_navigation:h.pause_on_navigation,
target:h.target||"new",value:h.url})};n3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,bh:z.card?g.vs(z.card):null,uf:z.teaser?g.vs(z.teaser):null,yc:z.icon?g.vs(z.icon):null,jo:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,
url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};n3(c,f);break;case "productListing":h.signin_url&&(D=X2({target:"current",value:h.signin_url}));F=[];for(var H=h.offers||[],U=0;U<H.length;U++)F.push(new Dwa(g.md(H[U].merchant),g.md(H[U].price)));f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,bh:z.card?
g.vs(z.card):null,uf:z.teaser?g.vs(z.teaser):null,yc:z.icon?g.vs(z.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Uo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),vU:D,uU:h.signin_title?h.signin_title:void 0,tU:h.signin_message?h.signin_message:void 0,offers:F};n3(c,f);break;case "simple":f=
{id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,bh:z.card?g.vs(z.card):null,uf:z.teaser?g.vs(z.teaser):null,yc:z.icon?g.vs(z.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Uo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};n3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bc:h.session_data||{},sponsored:h.sponsored||!1,ae:m,bh:z.card?g.vs(z.card):null,uf:z.teaser?g.vs(z.teaser):null,yc:z.icon?g.vs(z.icon):null,jo:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?
h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},n3(c,f)}}else Hwa(a.o,f);c=!0}}}c&&(A2(a.player),a.jr())},oxa=function(a,b){var c=!1;
a.o||(a.o=lxa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Iwa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.R(b.headerText):"",g.Fe(c.ya,d),c.I&&c.I.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.T=b.trackingParams?g.vs(b.trackingParams):null,c.G=b.closeButton.infoCardIconRenderer.trackingParams?g.vs(b.closeButton.infoCardIconRenderer.trackingParams):null,c.yc=b.icon.infoCardIconRenderer.trackingParams?g.vs(b.icon.infoCardIconRenderer.trackingParams):
null,A2(a.player),a.jr())},pxa=function(a,b,c,d,e){if(!a.player.O().Ha){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new vwa("openUrl","click",new twa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.R(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.R(b.subscriberCountText))):(b.subscriberCountText&&(e=g.R(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.R(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.R(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.R(b.subscribedButtonText),unsubscribeCount:h,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Z2(c,"branding","branding",f,d);d=cxa();a.u.element.appendChild(d);f=new r3(d,x3(a),f);f.Xn();g.C(f,f);a.G[c]=f}},ixa=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.R.push(g.vp(b))}},a)},D2={},E2=null;g.Ua(G2,g.Ln);g.k=G2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;F2(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.gr();this.df("play");-1==this.o&&this.df("resume");this.o=1;var b=g.Ra(this);b in D2||(D2[b]=this);dwa();ewa(this,a);return!0};
g.k.stop=function(a){F2(this);this.o=0;a&&(this.progress=1);fwa(this,this.progress);this.df("stop");this.Dn()};
g.k.pause=function(){this.sb()&&(F2(this),this.o=-1,this.df("pause"))};
g.k.X=function(){0==this.o||this.stop(!1);this.df("destroy");G2.tc.X.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.vv=function(){this.df("animate")};
g.k.df=function(a){this.dispatchEvent(new gwa(a,this))};
g.Ua(gwa,g.Qe);g.Ua(H2,G2);H2.prototype.B=g.Ka;H2.prototype.vv=function(){this.B();H2.tc.vv.call(this)};
H2.prototype.Dn=function(){this.B();H2.tc.Dn.call(this)};
H2.prototype.gr=function(){this.B();H2.tc.gr.call(this)};
g.Ua(I2,H2);I2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(J2,g.A);J2.prototype.ma=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.hp(a,b,c);this.o.push(a);return a};
J2.prototype.Iu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.qp(a,b,c);this.o.push(a);return a};
J2.prototype.ob=function(a){g.ip(a);g.kb(this.o,a)};
J2.prototype.X=function(){g.ip(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.t(N2,g.NN);g.k=N2.prototype;g.k.load=function(){g.NN.prototype.load.call(this);if(!O2(this)){var a=g.XB(this.player.getVideoData());if(a)a=M2(a,iwa(this)),P2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Ad:(0,g.x)(this.xL,this,a),Xe:{v:a},withCredentials:!0};this.N&&(a.Xe.ptype="embedded");var c=this.player.getVideoData().tp;c&&(a.Cb={ad_tracking:c});if(b=g.WB(b))if(b=g.Fc(b),b=g.Bc(b))this.B=g.vq(b,a)}}};
g.k.unload=function(){P2(this,null);this.B&&(this.B.abort(),this.B=null);g.NN.prototype.unload.call(this)};
g.k.gd=function(a,b){if(!O2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=M2(b,"new");P2(this,c);return!0}return null};
g.k.getOptions=function(){return O2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=M2(c,iwa(this)))}P2(this,c)};
g.k.JA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<qxa.length;f++){var h=Math.abs(b.width-qxa[f]);if(-1==e||d>=h)e=f,d=h}d=rxa[e];this.A&&g.Dh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Vh(e.element,Math.round(h.width*a.width),f);g.Lh(e.element,m,n);g.Kn(e.element,sxa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Kn(e.element,rxa);g.I(e.element,d);(e=g.ie(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Dh(e,"height",f+"px")}}}}};
g.k.hI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())T2(this,this.u.impressionUrls),(a=g.Bs())&&this.u.visualElement&&g.Ss(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");T2(this,c.impressionUrls);(b=g.Bs())&&g.Ss(b,c.visualElement);this.player.O().A&&this.player.oa("endscreenelementshown",a)}};
g.k.iI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Jn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Jn(b,"ytp-ce-shown");this.player.O().A&&this.player.oa("endscreenelementhidden",a)}};
g.k.WN=function(a){var b=this;a.target===window&&(new g.G(function(){for(var c in b.o)g.Kn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.VB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Hn(c,"ytp-ce-element");){g.Hn(c,"subscribe-label")&&U2(this,a);if(g.Hn(c,"ytp-ce-channel-subscribe"))return;c=g.De(c)}if(!c||g.Hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Bv(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.cP?(U2(this,a),this.AD(),this.player.pauseVideo(),c=g.Fc(R2(this,a.targetUrl)),c=g.Bc(c),g.oO(c,void 0,a.Bc)):(c=this.player.getVideoData().fc,
c=(0,g.x)(this.VO,this,c,R2(this,a.targetUrl),a.Bc),c=(0,g.x)(this.AD,this,c),U2(this,a,c))}}};
g.k.VO=function(a,b,c){var d=g.dq(b);a&&d&&(d.v||d.list)?g.tU(this.player.app,d.v,c,d.list,!1,void 0):g.nO(b,c)};
g.k.Qu=function(a,b){g.Hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.G(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),T2(this,b.sH),S2(this,b.id,!0))};
g.k.Bv=function(a,b){g.Jn(a.element,"ytp-ce-element-hover");g.Jn(a.element,"ytp-ce-force-expand");S2(this,b.id,!1)};
g.k.AD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var qxa=[346,426,470,506,570,640,853,1280,1920],rxa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sxa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var uwa={MQ:"current",jS:"new"};var wwa={CLOSE:"close",mS:"openUrl",nF:"subscribe"},xwa={CQ:"click",CLOSE:"close",uR:"hidden",XS:"rollOut",YS:"rollOver",eT:"shown"};Z2.prototype.xc=function(){var a=ywa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var nxa={kQ:"anchored",JE:"branding",CHANNEL:"channel",LQ:"cta",xR:"highlightText",MR:"label",PLAYLIST:"playlist",JS:"popup",kT:"speech",nF:"subscribe",wT:"title",VIDEO:"video",JT:"website"},mxa={JE:"branding",uQ:"card",RQ:"drawer",wR:"highlight",XR:"marker",OS:"promotion",TEXT:"text",LT:"widget"};g.t(f3,g.A);g.k=f3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Xy(a,b,{id:c});a.namespace="annotations_module";d&&this.fa.set(a,d);e&&this.ga.set(a,e);g.vN(this.context.H,[a])};
g.k.Xn=function(){this.context.u.subscribe("resize",this.Xo,this)};
g.k.xa=function(){return this.element};
g.k.Vu=function(a,b,c,d,e,f){if(this.sa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Be(this.xa())};
g.k.Xo=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Y2(a);if(f){var h=Fwa(f,a.target),l=function(){a.o&&e.context.H.pauseVideo();var m=e.context.videoData.fc||!1,n=g.dq(f||"");m&&n&&(n.v||n.list)?g.tU(e.context.H.app,n.v,b,n.list,!1,void 0):g.oO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);$2(this.context.logger,c,l,d);Ewa(f)||(c=g.Bs(),d=b.itct,c&&d&&g.Xs(c,g.vs(d)))}};
g.k.X=function(){this.fa.clear();this.ga.clear();g.A.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.C(this,a);return a.element};g.t(k3,f3);g.k=k3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.H.getRootNode())?(a=g.Wh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Xo=function(){var a=this.isAvailable();g.Xh(this.xa(),a);g.J(this.context.H.getRootNode(),g.ZL.IV_DRAWER_ENABLED,a);A2(this.H)};
g.k.destroy=function(){var a=g.oN(g.dN(this.H));a&&a.Ou(!1,void 0);try{this.H.getRootNode().removeChild(this.B)}catch(b){}g.To(this.N);g.ip(this.aa);this.ea&&this.ea.dispose();this.C&&this.C.dispose();f3.prototype.destroy.call(this)};
g.k.PF=function(){if(this.A){$2(this.context.logger,p3(this).ae.close);var a=g.Bs();a&&this.G&&g.Xs(a,this.G);j3(this)}};
g.k.gG=function(){g.J(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.KH=function(){var a=g.Bs(),b=p3(this);b=b?b.yc:this.yc;a&&b&&B2(a,[b])};
g.k.JH=function(){var a=g.Bs(),b=p3(this);b=b?b.yc:this.yc;a&&b&&C2(a,[b])};
g.k.UI=function(){var a=p3(this);$2(this.context.logger,a.ae.ND);var b=g.Bs();b&&a&&B2(b,[a.uf,a.yc])};
g.k.LH=function(){var a=g.Bs(),b=p3(this);a&&b&&C2(a,[b.uf])};
g.k.TI=function(a){var b=p3(this),c=g.Bs();this.o?a?(a=this.context.logger,$2(a,b.ae.Tr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.uf&&g.Xs(c,b.uf)):(a=this.context.logger,$2(a,b.ae.Tr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.yc&&g.Xs(c,b.yc)):(a=this.context.logger,$2(a,b.ae.Tr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.yc&&g.Xs(c,this.yc))};g.t(q3,f3);q3.prototype.Xn=function(){f3.prototype.Xn.call(this);Swa(this)};
q3.prototype.show=function(){f3.prototype.show.call(this);var a=g.Bs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.vs(b.itct)])};
q3.prototype.hide=function(){f3.prototype.hide.call(this);var a=g.Bs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&C2(a,[g.vs(b.itct)])};g.t(r3,q3);
r3.prototype.show=function(){if(!this.isActive){q3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",W:["branding-img","iv-click-target"],P:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Xh(this.u,!1);var b=this.createElement({D:"div",W:["branding-img-container"]});b.appendChild(this.u);this.xa().appendChild(b);(b=this.annotation.xc())&&g3(this,this.u,b,this.annotation.id,a.session_data);
Wwa(this,a);this.G=!0}g.Xh(this.xa(),!0);this.isActive=!0;this.u&&Twa(this,this.u)}};
r3.prototype.hide=function(){this.isActive&&(q3.prototype.hide.call(this),g.Xh(this.xa(),!1),this.isActive=!1)};
r3.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);q3.prototype.destroy.call(this)};g.t(s3,q3);g.k=s3.prototype;g.k.show=function(){this.isActive||(q3.prototype.show.call(this),this.M||(Ywa(this),this.M=!0),g.Xh(this.xa(),!0),g.cg(function(){g.Jn(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,u3(this),Zwa(this),$wa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden","true"))};
g.k.Vu=function(a,b,c,d,e,f){return this.isCollapsed?!1:q3.prototype.Vu.call(this,a,b,c,d,e,f)};
g.k.aH=function(a){this.I=!0;t3(this,500,a)};
g.k.ZG=function(){this.I=!1;axa(this)};
g.k.SG=function(a){a.stopPropagation();this.hide()};
g.k.TG=function(a){a.stopPropagation();u3(this);this.isCollapsed=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();q3.prototype.destroy.call(this)};g.t(v3,g.NN);g.k=v3.prototype;g.k.gd=function(a,b){if(!dxa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.y1(b);c&&w3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Kwa(this.o,b),A2(this.player)),!0}return null};
g.k.getOptions=function(){return dxa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.jr=function(){if(this.B){var a=g.iN(this.player).getVideoContentRect(!0);g.Vh(this.B.element,a.width,a.height);g.Lh(this.B.element,a.left,a.top)}if(this.o){var b=this.player.Vk();a=this.o;b=b.width;g.J(a.B,"iv-drawer-small",426>=b);g.J(a.B,"iv-drawer-big",1280<=b)}};
g.k.fI=function(a){exa(this,a.state);g.S(a.state,2)&&(this.ln()&&this.DA()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ou(!1))};
g.k.load=function(){g.NN.prototype.load.call(this);exa(this,g.iM(this.player));this.M++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.AL,this,b,this.M),d=(0,g.x)(function(){this.F=null},this);
g.xp()&&(c=ixa(this,c));c={format:"XML",Ad:c,onError:d,Xe:{}};a.isPharma&&(c.Xe.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().N.get(b))&&jxa(c,b);b=b&&(b.fp||b.ep);if(!a.Qo||b)a.cf?fxa(this,a.cf,c):(this.A=(0,g.x)(this.gI,this,c),this.player.addEventListener("videodatachange",this.A));g.zN(this.player,this.B.element,4);this.jr();(b=g.YB(a))&&oxa(this,b);(b=g.ZB(a))&&b.featuredChannel&&pxa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.k.gI=function(a){var b=this.player.getVideoData();b.cf&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),fxa(this,b.cf,a))};
g.k.unload=function(){g.rQ(this.player.app,"annotations_module",void 0);g.Ab(this.G,function(a){a.destroy()});
this.I=null;this.o&&(this.o.destroy(),this.o=null,A2(this.player));this.N=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.NN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.AL=function(a,b,c){this.F=null;!hxa(this,b,a)&&(a=g.pq(c)&&c.responseXML?c.responseXML:null)&&(w3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.k.EC=function(a){a==this.player.getVideoData().videoId&&(this.loaded?kxa(this):this.load())};
g.k.ln=function(){return!!this.o&&this.o.isAvailable()};
g.k.DA=function(){this.ln();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ln();this.o&&(a?c?i3(this.o,c,b):i3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):j3(this.o))};
g.k.Ou=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.X=function(){this.player.O().N.unsubscribe("vast_info_card_add",this.EC,this);g.Jn(this.player.getRootNode(),g.ZL.IV_DRAWER_OPEN);for(var a=this.R,b=0,c=a.length;b<c;b++)g.yp(a[b]);this.R.length=0;g.NN.prototype.X.call(this)};g.YN.annotations_module=v3;g.YN.creatorendscreen=N2;})(_yt_player);
