(function(g){var window=this;var B3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.yz(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},C3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},txa=function(a,b){var c=new g.xz;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},uxa=function(){this.u=[];
this.o=[]},D3=function(a,b){switch(b.kind){case "asr":vxa(b,a.u);
break;default:vxa(b,a.o)}},vxa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},E3=function(){g.A.call(this);
this.u=new uxa;this.B=[]},F3=function(a,b,c){E3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.Xs},G3=function(){this.segments=[]},wxa=function(a,b){var c=g.ub(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},H3=function(a,b,c,d,e,f){g.A.call(this);
this.policy=a;this.player=b;this.N=c;this.F=d;this.C=e;this.I=f;this.M=this.player.O();this.B=new G3;this.u=this.A=this.o=null;this.G=new g.G(this.tA,1E3,this);this.events=new g.es(this);g.C(this,this.G);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.wC);this.wC();this.tA()},xxa=function(a,b){var c=g.Jv(b,a.policy,{}).xc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Hr(c,d,3,100).then(function(e){a.ha();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.xw(e);h?(e=g.Jv(a.A,a.policy,{}),f=a.A,g.Fv(f.u,e,h),f.requestId=e.get("req_id"),xxa(a,a.A)):(f||null==a.F||(h=a.A.o[0],a.C?a.F(e.response,1E3*(h.startTime+a.player.Jb())):a.F(e.responseText,1E3*(h.startTime+a.player.Jb()))),a.A=null,a.u=null)});
a.A=b;wxa(a.B,a.A.o[0].u)},I3=function(a,b){E3.call(this,b.O());
this.ia=a;this.H=b;this.o=null;this.A=!1;this.C=g.Ly(this.H.O())&&!this.ia.u},yxa=function(a,b){var c=[],d;
for(d in a.ia.o)if(a.ia.o.hasOwnProperty(d)){var e=a.ia.o[d];if(g.ON(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.xz({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},zxa=function(a,b){return null!=b&&b in a.ia.o?a.ia.o[b]:null},Axa=function(a,b,c){var d=[],e;
for(e in a.ia.o)if(a.ia.o.hasOwnProperty(e)){var f=a.ia.o[e];if(g.ON(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},J3=function(a,b,c,d,e){E3.call(this,e||null);
this.videoId=b;this.Vz=d;this.C={};this.o=null;b=c||g.dq(a).hl||"";b=b.split("_").join("-");this.A=g.fq(a,{hl:b})},K3=function(a,b,c,d,e,f,h){var l={};
g.Ta(l,b);g.Ta(l,a.params);g.Ta(l,c);var m={};g.Ta(m,b.Lb);a.params.Lb&&g.Ta(m,a.params.Lb);g.Ta(m,c.Lb);l.Lb=m;g.T.call(this,{D:"div",J:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",J:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.U=!1;this.u=a;this.Y=this.T=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.F=null;this.maxWidth=.96*e;this.va=.96*f;this.o=l;this.Ea=
c;this.B=this.ca("captions-text");this.Da=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Z=d/360*16;this.type=0;this.ga=this.Z*Bxa(m);a=new g.ks(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.cJ,this);a.subscribe("dragmove",this.bJ,this);a.subscribe("dragend",this.aJ,this);this.sa=this.na=0;b="";this.o.windowOpacity&&(a=g.x1(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":Cxa[this.o.textAlign]};this.Da&&(a["border-radius"]=b?this.ga/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.pe&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Dh(b,"-o-writing-mode",c),g.Dh(b,"-webkit-writing-mode",c),g.Dh(b,"writing-mode",c),g.Dh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.Dh(b,"text-orientation",
""),g.Dh(b,"transform","rotate(180deg)"));g.Dh(this.element,a);switch(this.o.xf){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},Bxa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Dxa=function(a,b){var c={},d=b.background?b.background:a.o.Lb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.Lb.backgroundOpacity;d=g.x1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Da&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*Bxa(b)+"px";d=1;e=b.color||a.o.Lb.color;if(b.color||null!=b.textOpacity)e=g.x1(e),d=null==b.textOpacity?a.o.Lb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.ht&&(h=e=b.ht);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ll()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Lb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Of&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.rH&&(c.visibility="hidden");1===b.Sz&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Py||g.Qy,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.fg||2===b.fg||3===b.fg||4===b.fg||5===b.fg)if(g.Py)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.fg){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Exa=function(a){a.F=g.we("SPAN");
g.Dh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},Fxa=function(a,b){var c=g.we("SPAN");
g.Dh(c,{display:"inline-block","white-space":"pre-wrap"});g.Dh(c,Dxa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.Dh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Dh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Gxa=function(a,b,c){a.U=a.U||!!c;
var d={};g.Ta(d,a.o.Lb);g.Ta(d,c||b.o);g.Ta(d,a.Ea.Lb);(c=!a.F)&&Exa(a);for(var e=a.T&&a.Y&&g.Qb(d,a.Y)?a.T:Fxa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Exa(a),e=Fxa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.xe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.Py||!g.Hh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Hh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.re?g.Dh(e,m,"1em"):g.Dh(e,m,"0.5em")))}a.Y=d;a.T=e;a.C.push(b)},L3=function(a,b,c,d,e,f,h){K3.call(this,a,b,c,d,e,f,h);
this.type=1},M3=function(a,b,c,d,e,f,h){K3.call(this,a,b,c,d,e,f,h);
this.type=2;this.G=[];this.N=this.I=this.aa=0;this.R=NaN;this.ya=0;this.Ba=null;this.fa=new g.G(this.eN,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.fa);g.Dh(this.element,"overflow","hidden")},Hxa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Ixa=function(a){if(isNaN(a.R)){var b=a.o.bi;
if(b){var c=g.we("SPAN");g.Fe(c,"\u2013".repeat(b));g.Dh(c,Dxa(a,a.o.Lb));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},Jxa=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Kxa=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.N=Math.max(Ixa(a),a.ya,Hxa(a,a.B))},Lxa=function(a,b){Kxa(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!==a.aa){var d=0<c&&0===a.aa;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.fa.jb());g.Dh(a.B,"transform",Jxa(a,c));a.aa=c}Kxa(a)},N3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Xy.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},O3=function(a,b,c,d,e){g.Xy.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Mxa=function(a){var b="_"+P3++;
return new O3(0,0x8000000000000,0,b,a)},Oxa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.oc){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[q.getAttribute("p")];l=Nxa(l.textContent,n.textContent,q.textContent,f.textContent,h);return new N3(a,b,e,c,l,d,m)}switch(m.oc){case 9:case 10:m.fg=1;break;case 11:m.fg=2;break;case 12:m.fg=3;break;case 13:m.fg=4;break;case 14:m.fg=5}return new N3(a,b,e,c,l.textContent||"",d,m)},Nxa=function(a,b,c,d,e){var f=g.ll(),h=
f?g.we("DIV"):g.we("RUBY"),l=g.we("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.we("DIV"):g.we("RP");a.textContent=b;h.appendChild(a);b=f?g.we("DIV"):g.we("RT");b.textContent=c;h.appendChild(b);c=e.oc;if(10===c||11===c||12===c||13===c||14===c)if(g.Dh(b,"text-emphasis-style","filled circle"),g.Dh(b,"text-emphasis-color","currentcolor"),g.Dh(b,"webkit-text-emphasis","filled circle"),11===e.oc||13===e.oc)g.Dh(b,"webkit-text-emphasis-position","under left"),g.Dh(b,"text-emphasis-position","under left");c=!0;if(4===e.oc||7===e.oc||12===e.oc||
14===e.oc)g.Dh(h,"ruby-position","over"),g.Dh(h,"-webkit-ruby-position","before");else if(5===e.oc||6===e.oc||11===e.oc||13===e.oc)g.Dh(h,"ruby-position","under"),g.Dh(h,"-webkit-ruby-position","after"),c=!1;e=f?g.we("DIV"):g.we("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Dh(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Dh(f,"display","none"),f=f.nextElementSibling,g.Dh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Dh(h.lastElementChild,"display","none"),d?(g.Dh(h,"padding-top","0.6em"),g.Dh(f,"top","0")):(g.Dh(h,"padding-bottom","0.6em"),g.Dh(f,"bottom","0")));return h},Q3=function(){g.A.apply(this,arguments)},R3=function(a){Q3.call(this);
this.F=a;this.B={};this.M={};this.N={};this.C="_"+P3++;this.I={};this.u=this.o=null;this.G=!0},S3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},T3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},U3=function(a,b){var c=S3(a,b);
return void 0!==c?c:null},W3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return V3.test(c),c},Pxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.N[d]:a.F);d=U3(b,"mh");null!=d&&(c.ql=d);d=U3(b,"ju");null!=d&&(c.textAlign=d);d=U3(b,"pd");null!=d&&(c.o=d);d=U3(b,"sd");null!=d&&(c.A=d);d=W3(b,"wfc");null!=d&&(c.windowColor=d);d=S3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},Qxa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.M[d]);d=U3(b,"ap");null!=d&&(c.xf=d);d=S3(b,"cc");null!=d&&(c.bi=d);d=S3(b,"ah");null!=d&&(c.Oe=d);d=S3(b,"rc");null!=d&&(c.u=d);d=S3(b,"av");null!=d&&(c.jg=d);return c},Rxa=function(a,b,c,d){var e={};
g.Ta(e,Qxa(a,b));g.Ta(e,Pxa(a,b));d?g.Qb(e,a.F)?(d=a.C,e=a.F):d="_"+P3++:d=b.getAttribute("id")||"_"+P3++;a=S3(b,"t")+c;b=S3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.bi,e.bi=c;return new O3(a,b,0,d,e)},X3=function(a){Q3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},Y3=function(a){a=g.Vd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Sxa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.bi=b);if(2===f.o||3===f.o)b=f.u,f.u=f.bi,f.bi=b;return new O3(c,d,0,e,f)},$3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new Z3(this);this.C=new Z3(this);this.o=[];this.clear()},Uxa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{gj:a,
Yh:b,result:0};a=Txa[a];b=Txa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Yh===d;if(d)return{gj:a,Yh:b,result:1}}else if(b&128&&1<=a&&31>=a)return{gj:a,Yh:b,result:2};return{gj:a,Yh:b,result:3}},Wxa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Vxa(a.B,b,c,d))},Xxa=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Wxa(a,d.oy,d.py,b):1===d.type&&a.u&496&&Vxa(a.C,d.oy,d.py,b);a.o.length=0},a4=function(){this.type=0},b4=function(){this.state=this.Yh=this.gj=0},Yxa=function(){this.timestamp=this.o=0},c4=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new a4;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new Yxa}},d4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!==r.o){0===c&&(c=m,d=q);n=String.fromCharCode(r.o);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.o||32===q)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(q=a.A[h][m],r=q.o,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},cya=function(a,b){switch(a){case 0:return Zxa[(b&127)-32];
case 1:return $xa[b&15];case 2:return aya[b&31];case 3:return bya[b&31]}return 0},e4=function(a){return a.A[a.row][a.u]},f4=function(a,b,c){2<=b&&1<a.u&&(--a.u,e4(a).o=0);
var d=e4(a);d.timestamp=a.C.time+0;d.o=cya(b,c);32>a.u&&a.u++},dya=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},g4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},h4=function(a){a.row=0<a.o?a.o:1;
a.u=1;g4(a,0,15)},i4=function(a){this.A=a;
this.C=0;this.style=new a4;this.F=new c4(this.A);this.G=new c4(this.A);this.text=new c4(this.A);this.u=this.F;this.B=this.G;this.o=this.u},j4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(d4(d,c),h4(a.u),h4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(d4(d,c),g4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},eya=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},fya=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},Z3=function(a){this.u=a;
this.C=0;this.A=new i4(this.u);this.F=new i4(this.u);this.o=new b4;this.B=this.A},Vxa=function(a,b,c,d){a.o.update();
b=Uxa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.gj;c=b.Yh;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&f4(a,0,b),c&96&&f4(a,0,c),0!==b&&0!==c&&3===a.style.type&&d4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.gj=e,b.Yh=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;dya(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));g4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:f4(b.o,0,32);break a;case 48:57===c?(d=b.o,e4(d).o=0,32>d.u&&d.u++):f4(b.o,1,c&15)}break;case 2:c&32&&f4(b.o,2,c&31);break;case 3:c&32&&f4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:eya(b);
break;case 33:d=b.o;1<d.u&&(--d.u,e4(d).o=0);break;case 36:d=b.o;b=e4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:j4(b,2,d);break;case 38:j4(b,3,d);break;case 39:j4(b,4,d);break;case 40:f4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);h4(d);fya(b);break;case 43:fya(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:d4(a,d)}g4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;d4(a,d);dya(a,b,b+1,a.o-1);g4(a,a.row,1)}break;case 46:g4(b.B,0,15);break;case 47:d4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,eya(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},gya=function(){},k4=function(a,b,c){this.I=a;
this.G=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.I);this.A=[]},l4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},m4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},n4=function(a,b){Q3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new $3;this.o.u=1<<this.track},o4=function(a){if("string"===typeof a)return!1;
a=new k4(a,8,0);return hya(a)},hya=function(a){if(!(a.o<a.u.byteLength)||1380139777!==m4(a))return!1;
a.version=l4(a);if(1<a.version)return!1;l4(a);l4(a);l4(a);return!0},p4=function(){Q3.call(this)},iya=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Of=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var q=h.childNodes[n];if(3===q.nodeType)q=new N3(b,c,d,e.id,q.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(q),e.o.push(q);else{var r={};g.Ta(r,l);iya(a,b,c,d,e,!0,q,r,m)}}},q4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},jya=function(a,b,c,d){d=Object.assign({ql:0},d);
return new O3(a,b,c,"_"+P3++,d)},r4=function(a){g.A.call(this);
this.u=a;this.o=null},lya=function(a){var b={};
if(a=C3(a))b.lang=a,kya.test(a)&&(b.o=1);return b},u4=function(a){g.NN.call(this,a);
this.H=a;this.A=this.H.O();this.videoData=this.H.getVideoData();this.va=g.iN(this.H);this.B={Lb:{}};this.F={Lb:{}};this.R=[];this.M={};this.ea={};this.T=!1;this.na=g.PN(this.videoData,this.H);this.ya=!!this.videoData.captionTracks.length;this.Ba=!!this.videoData.lm;this.ga="3"===this.A.controlsType;this.u=this.G=this.I=this.aa=this.ra=null;this.fa=new r4(this.A);this.o=null;this.Y=new g.es(this);var b=null,c=g.po("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.co(c));this.storage=b;b=
a.app.B;c=!(!b||!b.fo());this.sa=!(!b||!b.rk());this.C=this.ga&&c&&!this.na;this.N=!this.C&&this.ga&&this.sa&&this.na;g.C(this,this.fa);this.C?this.Z=this.U=null:(this.U=new g.An(this.dE,void 0,this),g.C(this,this.U),this.Z=new g.G(this.BO,2E3,this),g.C(this,this.Z));g.C(this,this.Y);this.C||this.Y.L(a,"resize",this.Uw);this.Y.L(a,"onPlaybackAudioChange",this.TK);this.Y.L(a,g.$y("captions"),this.dJ,this);this.Y.L(a,"crx_captions",this.eJ,this);s4(this,t4(this,"display-settings")||{})},v4=function(a){if(1===
a.A.ai||1===a.videoData.ai||"alwayson"===g.QB(a.videoData,"yt:cc"))return!0;
if(2===a.A.ai){var b=t4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().Zs;return"ON"===c||"on"===g.QB(a.videoData,"yt:cc")},w4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Ap||"FORCED_ON"===c.Zs},y4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.Ba?!1:a.ya?!1:!0);c=a.u.yj(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.QB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(C3(c[f])===d[e])return c[f];return a.G&&a.G.xt?a.G.xt:(d=c.find(function(h){return h.isDefault}))?d:c[0]||x4(a)}return null},x4=function(a){return a.G&&a.G.Ap},z4=function(a){var b=x4(a);
return!!b&&a.o===b},mya=function(a,b){for(var c=a.H.app.B.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},B4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.T=c,a.T&&A4(a,"module-enabled",!!b));a.o=b;w4(a)&&(a.o=x4(a));a.load()},nya=function(a,b){var c=a.va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&kya.test(d)&&(b.params.o=1);d=a.va.getPlayerSize();switch(null!=b.params.ql?b.params.ql:1<b.o.length?1:0){case 1:return new L3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new M3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new K3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},s4=function(a,b,c){c=void 0===c?!1:c;
var d=C4.Lb;a.B={};g.Ta(a.B,C4);a.B.Lb={};g.Ta(a.B.Lb,d);a.F={Lb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;V3.test(f);e.Lb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;V3.test(f);e.Lb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||C4.windowColor;V3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Lb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Lb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Of?3:d.bold?1:d.Of?2:0);f=f.Lb;switch(e){case 1:f.bold=!0;delete f.Of;break;case 2:delete f.bold;f.Of=!0;break;case 3:f.bold=!0;f.Of=!0;break;default:delete f.bold,delete f.Of}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Lb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=C4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Lb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Lb.fontFamily=f;a.loaded&&a.Uw();c&&A4(a,"display-settings",b)},pya=function(a,b){if(b&&!a.I){var c=Mxa({o:0,
lang:"en"});a.I=[c,new N3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.vN(a.player,a.I)}else!b&&a.I&&(oya(a,a.I),a.I=null)},oya=function(a,b){g.xU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.kb(this.R,c)},a);
a.U.jb()},t4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},A4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.AC.prototype.nm=g.ca(11,function(){for(var a=g.ie(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Be(a[b])});
g.EC.prototype.nm=g.ca(10,function(){this.o.nm()});
g.AC.prototype.fo=g.ca(9,function(){return!!this.o.textTracks});
g.EC.prototype.fo=g.ca(8,function(){return this.o.fo()});
g.AC.prototype.gm=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.EC.prototype.gm=g.ca(6,function(a){this.o.gm(a)});
g.rC.prototype.rk=g.ca(5,function(){});
g.AC.prototype.rk=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.EC.prototype.rk=g.ca(3,function(){return this.o.rk()});
g.kt.prototype.Pp=g.ca(1,function(a){return(a=this.sg(a))?a.o:0});
g.pw.prototype.Pp=g.ca(0,function(){return 0});
var kya=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;uxa.prototype.yj=function(a){return a?this.o.concat(this.u):this.o};
g.t(E3,g.A);g.k=E3.prototype;g.k.yj=function(a){return this.u.yj(a)};
g.k.rq=function(){};
g.k.tq=function(){};
g.k.Nh=function(){};
g.k.Uk=function(){return""};
g.k.SC=function(){return!1};
g.k.X=function(){this.Nh();g.A.prototype.X.call(this)};
g.t(F3,E3);F3.prototype.rq=function(a,b,c){var d=this;this.ha();b=this.Uk(a,b);this.Nh();this.o=g.vq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
F3.prototype.tq=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
F3.prototype.Uk=function(a,b){var c=a.xc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.ll()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=C3(a));return g.fq(c,d)};
F3.prototype.Nh=function(){this.o&&this.o.abort()};
G3.prototype.contains=function(a){a=g.ub(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G3.prototype.length=function(){return this.segments.length/2};
g.t(H3,g.A);g.k=H3.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.k.wC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Jb();var b=this.o;this.o=g.ab(this.N.oh(a).o);b!==this.o&&this.I&&this.I()};
g.k.reset=function(){this.B=new G3;this.u&&(this.u.cancel(),this.u=null)};
g.k.tA=function(){this.ha();var a;if(a=null!=this.o)a=this.o,a=a.o.Fh(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ki(),a.o[0].duration?(this.B.contains(a.o[0].u)||xxa(this,a),this.o=g.ab(a.o)):!g.P(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.C&&this.o.C+this.player.Jb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.t(I3,E3);g.k=I3.prototype;g.k.rq=function(a,b,c){var d=this;this.Nh();b=zxa(this,a.getId());b||(b=a.languageCode,b=this.ia.u?Axa(this,b,"386"):Axa(this,b));if(b){var e=1E3*(b.index.Pp(b.index.If())-b.index.zd(b.index.If()));this.o=new H3(new g.av,this.H,b,function(f,h){c(f,a,h,e)},this.C||g.Ru(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.SC=function(){var a=this.A;this.A=!1;return a};
g.k.tq=function(a){var b;this.C?b=[new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ia.u?yxa(this,"386"):yxa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
g.k.Nh=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.Uk=function(){return""};
g.t(J3,E3);J3.prototype.rq=function(a,b,c){var d=this;this.ha();b=this.Uk(a,b);this.Nh();this.o=g.vq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
J3.prototype.tq=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Vz&&(d.asrs=1);c=g.fq(c,d);this.Nh();this.o=g.vq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),r=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),B="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");D3(b.u,new g.xz({languageCode:m,languageName:n,name:q,kind:r,id:u,is_servable:!0,is_translateable:B,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
J3.prototype.Uk=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=C3(a));return c=g.fq(c,d)};
J3.prototype.Nh=function(){this.o&&this.o.abort()};
var V3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Cxa=["left","right","center","justify"];g.t(K3,g.T);g.k=K3.prototype;g.k.cJ=function(a,b){var c=g.Th(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.bJ=function(a,b){var c=g.Wh(this.element),d=a-this.na-.02*this.playerWidth,e=b-this.sa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Vd(f,0,2));var h=(e+c.height/2)/this.va*3;h=Math.floor(g.Vd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Vd(d,0,1);c=(e+h/2*c.height)/this.va;c=100*g.Vd(c,0,1);this.u.params.xf=l;this.u.params.jg=c;this.u.params.Oe=d;this.o.xf=l;this.o.jg=c;this.o.Oe=d;this.vD()};
g.k.aJ=function(){g.Jn(this.element,"ytp-dragging")};
g.k.vD=function(){this.nk(this.C)};
g.k.nk=function(a){var b=Math.min(this.lz(),this.maxWidth),c=this.kz(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.Dh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Rs(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Oe+2;d=this.o.xf;switch(d){case 0:case 3:case 6:b=this.o.Lb.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.jg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.Dh(this.element,a)};
g.k.Rs=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.U||this.C.length>b)b=0,this.U=!1,this.C=[],this.F=this.Y=this.T=null,g.ze(this.B);for(;b<a.length;b++)Gxa(this,a[b])};
g.k.lz=function(){return 0};
g.k.kz=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};g.t(L3,K3);L3.prototype.Rs=function(a){var b=this.u.o;K3.prototype.Rs.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,qya);var e=c.o;var f=d}Gxa(this,c,d)}};
var qya={rH:!0};g.t(M3,K3);g.k=M3.prototype;g.k.vD=function(){g.Dn(this.fa)};
g.k.eN=function(){g.Jn(this.element,"ytp-rollup-mode");this.nk(this.Ba,!0)};
g.k.kz=function(){return this.A?this.N:this.I};
g.k.lz=function(){return this.A?this.I:this.N};
g.k.nk=function(a,b){this.Ba=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.N;this.I=this.N=0;K3.prototype.nk.call(this,a);Lxa(this,b);K3.prototype.nk.call(this,a)}else K3.prototype.nk.call(this,a)};g.t(N3,g.Xy);N3.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};g.t(O3,g.Xy);O3.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};
var P3=0;g.t(Q3,g.A);Q3.prototype.A=function(){return[]};
Q3.prototype.reset=function(){};g.t(R3,Q3);R3.prototype.reset=function(){this.I={};this.u=this.o=null;this.G=!0};
R3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Ta(l,this.B[m]);m=T3(c,"b");null!=m&&
(l.bold=m);m=T3(c,"i");null!=m&&(l.Of=m);m=T3(c,"u");null!=m&&(l.underline=m);m=U3(c,"et");null!=m&&(l.charEdgeStyle=m);m=U3(c,"of");null!=m&&(l.offset=m);m=W3(c,"bc");null!=m&&(l.background=m);m=W3(c,"ec");null!=m&&(l.ht=m);m=W3(c,"fc");null!=m&&(l.color=m);m=U3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=S3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=S3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=S3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=U3(c,"rb");null!=m&&10!==m&&0!==m&&(l.oc=
10<m?m-1:m);c=U3(c,"hg");null!=c&&(l.Sz=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.N[d]=Pxa(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=Qxa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=Rxa(this,d,e,!1);(d=this.I[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.I[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!T3(d,
"a");n=(S3(d,"t")||0)+n;var q=S3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var B=0;B<w.length;B++){var z=w[B],D=void 0;0<B&&(m=!0);var F=void 0;1===z.nodeType&&(F=z);if(F&&"s"===F.tagName){if((z=(z=F.getAttribute("p"))?this.B[z]:null)&&z.oc&&(1===z.oc?(z=w.slice(B,B+4),4===z.length&&
(D=Oxa(n,q,l,m,r,z,this.B),B+=3)):D=Oxa(n,q,l,m,r,[F],this.B)),!D){var H=F;D=n;F=q;z=l;var U=m,Z=r,nc=H.textContent?H.textContent:"",oc=H.getAttribute("p");oc=oc?this.B[oc]:null;H=S3(H,"t")||0;D=new N3(D+H,F-H,Z,z,nc,U,oc)}}else D=new N3(n,q,r,l,z.textContent||"",m,u);h.push(D);this.u=D}if(0<h.length)for(h[0].windowId===this.C&&(this.o=Rxa(this,d,e,!0),c.push(this.o)),d=g.p(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var rya=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.t(X3,Q3);X3.prototype.reset=function(){this.u.clear()};
X3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Of=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.ht=Y3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=Y3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=Y3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.oc=10<l?l-1:l,h.fg=rya.get(h.oc));f.hgHorizGroup&&(h.Sz=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.F),void 0!==f.mhModeHint&&(h.ql=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=Y3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Oe=f.ahHorPos),void 0!==f.apPoint&&(h.xf=f.apPoint),void 0!==f.avVerPos&&(h.jg=f.avVerPos),void 0!==f.ccCols&&(h.bi=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=Sxa(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+P3++,l=Sxa(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,q=n?6:5,r=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],B=w.utf8;if(B){var z=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.o.get(w.pPenId));if(2===(null!=l.params.ql?l.params.ql:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(w=D&&1===D.oc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var F=r[w+1].pPenId;(F=this.o.get(F))&&F.oc&&2===F.oc?(F=r[w+2].pPenId,F=this.o.get(F),!F||!F.oc||3>F.oc?w=!1:(F=r[w+3].pPenId,w=(F=this.o.get(F))&&
F.oc&&2===F.oc?!0:!1)):w=!1}if(w){z=r[m+1].utf8;w=r[m+3].utf8;F=r[m+2].utf8;var H=this.o.get(r[m+2].pPenId);B=Nxa(B,z,F,w,H);n=new N3(e,f,q,h,B,n,D);m+=3}else n=new N3(e+z,f-z,q,l.id,B,n,D||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};$3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
$3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Txa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];a4.prototype.set=function(a){this.type=a};
a4.prototype.get=function(){return this.type};
b4.prototype.clear=function(){this.state=0};
b4.prototype.update=function(){this.state=2===this.state?1:0};
b4.prototype.isValid=function(){return 0!==this.state};
b4.prototype.matches=function(a,b){return this.isValid()&&a===this.gj&&b===this.Yh};
Yxa.prototype.reset=function(){this.timestamp=this.o=0};
c4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
c4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
c4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var Zxa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],$xa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],aya=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],bya=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];i4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Z3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};gya.prototype.C=function(){};g.t(k4,gya);k4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+P3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new O3(c,d-c,5,f,{textAlign:0,xf:0,Oe:2.5*b,jg:5.33*a});e=new N3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.t(n4,Q3);n4.prototype.A=function(a){a=new k4(a,a.byteLength,this.u);if(hya(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=m4(a)*(1E3/45):1===a.version&&(a.B=4294967296*m4(a)+m4(a)),a.F=l4(a);0<a.F;a.F--){var b=l4(a),c=l4(a),d=l4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,oy:c,py:d,order:b.o.length}))}Xxa(this.o,a);return a.A}return[]};
n4.prototype.reset=function(){this.o.clear()};g.t(p4,Q3);
p4.prototype.A=function(a,b){for(var c=[],d=a.split(sya),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!tya.test(f)){var l=D4.exec(f);if(l&&4<=l.length){var m=q4(l[1]),n=q4(l[2])-m;m+=h;var q=(l=l[3])?l.split(" "):[];l={};var r=null,u="",w=null,B="";l.textAlign=2;q=g.p(q);for(var z=q.next();!z.done;z=q.next())if(z=z.value.split(":"),2===z.length){var D=z[1];switch(z[0]){case "line":z=D.split(",");z[0].endsWith("%")&&(r=z[0],l.jg=Number.parseInt(r,10),2===z.length&&(u=z[1].trim()));break;case "position":z=
D.split(",");w=z[0];l.Oe=Number.parseInt(w,10);2===z.length&&(B=z[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.jg=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.Oe=0;break;case 1:l.Oe=100;break;default:l.Oe=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(B){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.xf=0>r||8<r?7:r;f=f.substring(D4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");B=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=jya(m,n,5,B),n=new N3(m,n,5,h.id,l,!1,g.Ob(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(u=l.split(uya),1===u.length?(l=5,B=jya(m,n,l,B)):(r=l=6,B=Object.assign({bi:32},B),B=new O3(m,n,r,"_"+P3++,B)),c.push(B),r=m,w=0;w<u.length;w++)q=u[w],0===w%2?(z=g.y1("<html>"+q+"</html>"),z.getElementsByTagName("parsererror").length?
(D=z.createElement("span"),D.appendChild(z.createTextNode(q))):D=z.firstChild,iya(this,r,n-(r-m),l,B,0<w,D,f,c)):r=q4(q)+h}D4.lastIndex=0}}return c};
var tya=/^NOTE/,sya=/(?:\r\n|\r|\n){2,}/,D4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),uya=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(r4,g.A);r4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
r4.prototype.reset=function(){this.o&&this.o.reset()};
r4.prototype.X=function(){g.A.prototype.X.call(this);this.clear()};var C4={windowColor:"#080808",windowOpacity:0,textAlign:2,xf:7,Oe:50,jg:100,Lb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(u4,g.NN);g.k=u4.prototype;g.k.X=function(){if(this.C||this.N){var a=this.H.app.B;a&&!a.ha()&&a.nm()}else pya(this,!1);g.NN.prototype.X.call(this)};
g.k.load=function(){var a=this;g.NN.prototype.load.call(this);var b=!g.P(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.fa.clear(),this.C?mya(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.rq(this.o,"json3",function(d,e,f,h){if(d){a.u.SC()&&(a.R=[],g.rQ(a.H.app,"captions",void 0),a.U.jb(),a.fa.reset());var l=a.fa;f=f||0;h=h||0;if(l.u.da("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Ct(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),o4(d)||(d=g.hg(new Uint8Array(d))))}}else"string"===typeof d||o4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Ct(m,0,1835295092))&&m.size?g.hg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,r=h;if(!o4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new n4(r,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.o||(l.o=new p4),q=l.o.A(e,r),.01>Math.random()&&g.rr(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new X3(lya(e)));n=l.o.A(q,f);break b}catch(H){g.qr(H);n=[];break b}r=g.y1(q);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.o||(l.o=new R3(lya(e),l.u));n=l.o.A(r,f);break b}var B=Error("Unsupported subtitles format in web player (Format2)");
B.params=q;throw B;}if("transcript"===r.firstChild.tagName){var z=Error("Unsupported subtitles format in web player (Format1)");z.params=q;throw z;}var D=Error("Invalid caption track data");D.params=q;throw D;}u=n}var F=u}catch(H){g.qr(H),l.clear(),F=[]}else F=[];g.vN(a.player,F);!a.T||a.N||z4(a)||g.zy(a.A)||g.Ay(a.A)||(a.Z.Gf(),F=Mxa({xf:0,Oe:5,jg:5,u:2,textAlign:0,o:0,lang:"en"}),a.aa=[F],l=["Click "," for settings"],a.ra||(u=new g.VL(g.HM()),g.C(a,u),a.ra=u.element),u=F.end-F.start,(e=g.yz(a.o))&&
a.aa.push(new N3(F.start,u,0,F.id,e)),a.aa.push(new N3(F.start,u,0,F.id,l[0]),new N3(F.start,u,0,F.id,a.ra,!0),new N3(F.start,u,0,F.id,l[1],!0)),g.vN(a.player,a.aa),a.Z.jb());!a.T||a.N||z4(a)||(A4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.V(a.player.app))&&g.TI(F.F));a.T=!1}}),!b||this.C||this.N||z4(this)||this.player.oa("captionschanged",B3(this.o))),b||(this.o&&!z4(this)?this.player.oa("captionschanged",B3(this.o)):this.player.oa("onCaptionsTrackListChanged"));
else{var c;this.na?c=new I3(this.videoData.ia,this.player):this.ya?c=new F3(this.A,this.videoData,this.player.getAudioTrack()):c=new J3(this.videoData.lm,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.QB(this.videoData,"yt:cc_default_lang")||this.A.ce,this.videoData.Ys,this.A);this.u=c;g.C(this,this.u);c.tq(function(){var d;a.T||v4(a)?d=y4(a,a.T):w4(a)&&(d=x4(a));if(a.C||a.N){for(var e=a.u.yj(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.ve("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.yz(l));m.setAttribute("srclang",C3(l));m.setAttribute("id",l.toString());a.N||m.setAttribute("src",a.u.Uk(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.H.app.B;d.gm(f);f=d.xa();a.sa&&a.Y.L(f.textTracks,"change",a.GN)}else!a.o&&d&&B4(a,d),a.player.oa("onCaptionsTrackListChanged"),a.player.oa("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?mya(this,!1):(this.Z&&this.Z.Gf(),g.rQ(this.player.app,"captions",void 0),this.R=[],this.u&&this.u.Nh(),this.fa.clear(),this.I&&g.vN(this.player,this.I),this.Uw());g.NN.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.TI(a.F);this.player.oa("captionschanged",{})};
g.k.create=function(){(this.ga?this.C||this.N:w4(this)||v4(this))&&this.load()};
g.k.getTrackById=function(a){for(var b=this.u.yj(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.k.GN=function(){for(var a=this.H.app.B.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&B4(this,b,!0)};
g.k.nP=function(){!this.o&&this.C||this.unload()};
g.k.dJ=function(a){this.R.push(a);this.U.jb()};
g.k.eJ=function(a){g.kb(this.R,a);this.u instanceof I3&&this.u.C&&g.xU(this.player.app,[a],void 0);this.U.jb()};
g.k.uO=function(a){if(a instanceof O3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=nya(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.ea[b]||(this.ea[b]=[]),this.ea[b].push(a)};
g.k.BO=function(){oya(this,this.aa);this.aa=null};
g.k.dE=function(){var a=this;this.U.stop();g.Pb(this.ea);this.R.sort(g.Zy);var b=this.R;if(this.I){var c=(0,g.Ce)(b,function(d){return-1===this.I.indexOf(d)},this);
c.length&&(b=c)}(0,g.y)(b,this.uO,this);g.Ab(this.M,function(d,e){a.ea[e]?(d.element.parentNode||(d instanceof M3||d instanceof L3||g.Db(a.M,function(f,h){h!==e&&f.u.params.xf===d.u.params.xf&&f.u.params.Oe===d.u.params.Oe&&f.u.params.jg===d.u.params.jg&&(f.dispose(),delete a.M[h]);return h===e},a),g.zN(a.player,d.element,4)),d.nk(a.ea[e])):(d.dispose(),delete a.M[e])},this)};
g.k.HO=function(){s4(this,{},!0);g.P(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.oa("captionssettingschanged")};
g.k.KG=function(){var a=C4.Lb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Of?3:a.bold?1:a.Of?2:0,textOpacity:a.textOpacity,windowColor:C4.windowColor,windowOpacity:C4.windowOpacity};var b=t4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.lE=function(a,b){var c={};g.Ta(c,t4(this,"display-settings"));g.Ta(c,a);s4(this,c,b);this.player.oa("captionssettingschanged")};
g.k.Uw=function(){!this.C&&this.loaded&&(g.Ab(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.dE())};
g.k.gd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Vd(b,-2,4);this.lE({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&B4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&A4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.Ob(b)){B4(this,null,!0);break}for(var d=this.u.yj(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
txa(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||B4(this,c,!0)}else return this.loaded&&this.o&&!z4(this)?B3(this.o):{};return"";case "tracklist":return this.u?(0,g.Lc)(this.u.yj(!(!b||!b.includeAsr)),function(h){return B3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||pya(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.UH=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.gP=function(){this.loaded&&this.o&&!z4(this)?(A4(this,"module-enabled",!1),this.unload(),w4(this,!0)&&B4(this,x4(this),!1)):B4(this,z4(this)||!this.o?y4(this,!0):this.o,!0)};
g.k.TK=function(){var a=z4(this);w4(this,a)?B4(this,this.player.getAudioTrack().Ap,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.ga?this.C||this.N:w4(this)||v4(this))&&(a?B4(this,y4(this),!1):this.load()))};g.YN.captions=u4;})(_yt_player);
